/**
 * meeting
 * aca
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mariadelosangelesportal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Opciones, \'id\'>, schemaOptions: { title: \'NewOpciones\', exclude: [ \'id\' ] })
 */
export interface NewOpciones { 
  [key: string]: object | any;


    date?: string;
    eventoId?: string;
}

