/**
 * meeting
 * aca
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mariadelosangelesportal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<Opciones>, schemaOptions: { partial: true })
 */
export interface OpcionesPartial { 
  [key: string]: object | any;


    id?: string;
    date?: string;
    eventoId?: string;
}

