/**
 * meeting
 * aca
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mariadelosangelesportal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuarioFilter { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: string | Array<string>;
    fields?: any | Array<string>;
}

