/**
 * meeting
 * aca
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mariadelosangelesportal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Usuario { 
  [key: string]: object | any;


    id?: string;
    nombre?: string;
    apellido?: string;
    mail?: string;
    password?: string;
    eventos?: Array<object>;
}

