/**
 * meeting
 * aca
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mariadelosangelesportal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OpcionesWithRelations } from './opcionesWithRelations';


/**
 * (tsType: EventoWithRelations, schemaOptions: { includeRelations: true })
 */
export interface EventoWithRelations { 
  [key: string]: object | any;


    id?: string;
    nombre: string;
    descripcion?: string;
    opciones?: Array<OpcionesWithRelations>;
}

