/**
 * meeting
 * aca
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mariadelosangelesportal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Opciones, \'id\'>, \'eventoId\'>, schemaOptions: { title: \'NewOpcionesInEvento\', exclude: [ \'id\' ], optional: [ \'eventoId\' ] })
 */
export interface NewOpcionesInEvento { 
  [key: string]: object | any;


    date?: string;
    eventoId?: string;
}

